import { ShieldCheck, TriangleAlert } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { RetryMetaButton } from "@/components/operation-buttons";
import { PageHeading } from "@/components/page-heading";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getWorkspaceData } from "@/lib/data";

export default async function MetaEventsPage() {
  const data = await getWorkspaceData(); const storeNames = new Map(data.stores.map((store) => [store.id, store.name]));
  return <AppShell><div className="space-y-7 pb-20 lg:pb-0"><PageHeading eyebrow="Conversions API" title="Meta events" description="Monitor Purchase delivery and retry eligible Test Events." actions={["admin","operator"].includes(data.user.role) ? <RetryMetaButton /> : undefined} />
    <div className="grid gap-4 md:grid-cols-2"><Card className="border-primary/15 bg-primary/[0.05] shadow-none"><CardContent className="flex gap-3 p-5"><ShieldCheck className="mt-0.5 size-5 text-primary" /><div><p className="font-medium text-primary">Production sending is locked</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Only events carrying Meta’s Test Event code are eligible while the global gate is off.</p></div></CardContent></Card><Card className="border-amber-400/15 bg-amber-400/[0.04] shadow-none"><CardContent className="flex gap-3 p-5"><TriangleAlert className="mt-0.5 size-5 text-amber-300" /><div><p className="font-medium text-amber-200">Deduplication check required</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Disable Releasit server Purchase and prove a shared browser/server event_id before live activation.</p></div></CardContent></Card></div>
    <Card className="border-white/[0.07] bg-card/60 shadow-none"><CardHeader><CardTitle>Delivery log</CardTitle><CardDescription>Unique event ID per store and Shopify order</CardDescription></CardHeader><CardContent className="overflow-x-auto px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">Event ID</TableHead><TableHead>Store</TableHead><TableHead>Mode</TableHead><TableHead>Attempts</TableHead><TableHead>Status</TableHead><TableHead>Last attempt</TableHead></TableRow></TableHeader><TableBody>{data.events.map((event) => <TableRow key={String(event.id)}><TableCell className="max-w-64 truncate pl-6 font-mono text-xs">{event.event_id}</TableCell><TableCell>{storeNames.get(event.store_id) ?? "Store"}</TableCell><TableCell><Badge variant="secondary">{event.is_test ? "Test" : "Production"}</Badge></TableCell><TableCell>{event.attempt_count}</TableCell><TableCell><Badge variant="outline" className={event.status === "sent" ? "border-emerald-400/20 text-emerald-400" : event.status === "failed" ? "border-destructive/30 text-destructive" : "border-amber-400/20 text-amber-300"}>{event.status}</Badge></TableCell><TableCell className="text-muted-foreground">{event.last_attempt_at ? new Date(String(event.last_attempt_at)).toLocaleString("en-IN") : "Waiting"}</TableCell></TableRow>)}</TableBody></Table>{!data.events.length && <p className="p-6 text-sm text-muted-foreground">New webhook-created orders will appear here after a Meta Test Events connection is configured.</p>}</CardContent></Card>
  </div></AppShell>;
}
