import Link from "next/link";
import { BadgeIndianRupee, CircleCheckBig, Download, PackageOpen, RadioTower, ShoppingCart, TriangleAlert } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { campaignRows, getWorkspaceData, money, summarize } from "@/lib/data";

export default async function DashboardPage() {
  const data = await getWorkspaceData(); const summary = summarize(data.orders, data.events); const campaigns = campaignRows(data.orders).slice(0, 5);
  const metrics = [
    { label: "Gross sales", value: money(summary.gross), Icon: BadgeIndianRupee }, { label: "Orders", value: summary.count.toLocaleString("en-IN"), Icon: ShoppingCart },
    { label: "COD share", value: `${summary.codShare.toFixed(1)}%`, Icon: PackageOpen }, { label: "Meta delivery", value: `${summary.deliveryRate.toFixed(1)}%`, Icon: RadioTower },
  ];
  return <AppShell><div className="space-y-7 pb-20 lg:pb-0">
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-sm text-primary">Live operations</p><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Welcome, {data.user.fullName?.split(" ")[0] ?? "Admin"}</h1><p className="mt-2 text-sm text-muted-foreground">Shopify orders and Meta server-event health for the last 30 days.</p></div><Button variant="outline" asChild><Link href="/api/exports/orders?format=csv"><Download className="size-4" /> Export</Link></Button></section>
    {!data.stores.length && <Card className="border-dashed border-primary/30 bg-primary/[0.04]"><CardContent className="flex flex-col items-start gap-3 p-6"><p className="font-medium">Connect your first store</p><p className="text-sm text-muted-foreground">Add encrypted Shopify and optional Meta Test Events credentials to start importing orders.</p><Button asChild><Link href="/stores">Open store setup</Link></Button></CardContent></Card>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, Icon }) => <Card key={label} className="border-white/[0.07] bg-card/60 shadow-none"><CardContent className="p-5"><div className="mb-5 flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><span className="grid size-9 place-items-center rounded-lg bg-white/[0.04]"><Icon className="size-4 text-primary" /></span></div><span className="text-2xl font-semibold tracking-tight">{value}</span><p className="mt-1 text-[11px] text-muted-foreground">Last 30 days</p></CardContent></Card>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.55fr_1fr]"><Card className="min-w-0 border-white/[0.07] bg-card/60 shadow-none"><CardHeader><CardTitle>Recent orders</CardTitle><CardDescription>Latest orders received from Shopify</CardDescription></CardHeader><CardContent className="overflow-x-auto px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">Order</TableHead><TableHead>Campaign</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader><TableBody>{data.orders.slice(0, 8).map((order) => <TableRow key={String(order.id)}><TableCell className="pl-6 font-medium">{order.shopify_order_number}</TableCell><TableCell className="font-mono text-xs text-muted-foreground">{order.utm_campaign ?? "Unattributed"}</TableCell><TableCell><Badge variant="secondary" className="capitalize">{String(order.status).replaceAll("_", " ")}</Badge></TableCell><TableCell className="text-right">{money(Number(order.total), String(order.currency))}</TableCell></TableRow>)}</TableBody></Table>{!data.orders.length && <Empty text="No orders imported yet." />}</CardContent></Card>
      <Card className="border-white/[0.07] bg-card/60 shadow-none"><CardHeader><CardTitle>Attribution health</CardTitle><CardDescription>Server event processing status</CardDescription></CardHeader><CardContent className="space-y-5"><div className="rounded-xl border border-primary/15 bg-primary/[0.06] p-4"><div className="flex items-center gap-2 text-sm font-medium text-primary"><CircleCheckBig className="size-4" /> Test-only safety is active</div><p className="mt-1.5 text-xs leading-5 text-muted-foreground">Live Purchase delivery remains locked globally and per store.</p></div>{[["Sent",summary.sent,summary.deliveryRate],["Failed / retrying",summary.failed,summary.failed ? 100-summary.deliveryRate : 0]].map(([label,value,percent]) => <div key={String(label)}><div className="mb-2 flex justify-between text-sm"><span className="text-muted-foreground">{label}</span><span>{value}</span></div><Progress value={Number(percent)} className="h-1.5" /></div>)}</CardContent></Card></div>
    <Card className="border-white/[0.07] bg-card/60 shadow-none"><CardHeader><CardTitle>Top UTM campaigns</CardTitle><CardDescription>Shopify-reported order revenue</CardDescription></CardHeader><CardContent className="space-y-5">{campaigns.map((campaign) => <div key={campaign.name} className="grid gap-2 sm:grid-cols-[1fr_100px_140px]"><span className="truncate font-mono text-xs">{campaign.name}</span><span className="text-xs text-muted-foreground">{campaign.orders} orders</span><span className="text-sm font-medium sm:text-right">{money(campaign.revenue)}</span></div>)}{!campaigns.length && <p className="text-sm text-muted-foreground">Campaign totals appear after orders are imported.</p>}<div className="flex gap-2 rounded-lg border border-amber-400/15 bg-amber-400/[0.04] p-3 text-xs text-amber-200/80"><TriangleAlert className="size-4 shrink-0" /> UTM reporting is directional; Meta remains the attribution source of truth.</div></CardContent></Card>
  </div></AppShell>;
}

function Empty({ text }: { text: string }) { return <p className="p-6 text-sm text-muted-foreground">{text}</p>; }
