import Link from "next/link";
import { Download, Truck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeading } from "@/components/page-heading";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { campaignRows, getWorkspaceData, money, summarize } from "@/lib/data";

export default async function ReportsPage() {
  const data = await getWorkspaceData(); const summary = summarize(data.orders, data.events); const campaigns = campaignRows(data.orders); const max = campaigns[0]?.revenue || 1;
  return <AppShell><div className="space-y-7 pb-20 lg:pb-0"><PageHeading eyebrow="Reporting" title="Performance reports" description="Store, status and UTM performance. Shopify remains the order source of truth." actions={<Button asChild><Link href="/api/exports/orders?format=xlsx"><Download className="size-4" /> Export Excel</Link></Button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Gross sales",money(summary.gross)],["Net after refunds",money(summary.net)],["Average order",money(summary.average)],["COD share",`${summary.codShare.toFixed(1)}%`]].map(([key,value]) => <Card key={key} className="border-white/[0.07] bg-card/60 shadow-none"><CardContent className="p-5"><p className="text-xs text-muted-foreground">{key}</p><p className="mt-2 text-2xl font-semibold">{value}</p></CardContent></Card>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_1fr]"><Card className="border-white/[0.07] bg-card/60 shadow-none"><CardHeader><CardTitle>Order lifecycle</CardTitle><CardDescription>Current Shopify status for orders in the reporting window</CardDescription></CardHeader><CardContent className="space-y-4">{lifecycleRows(data.orders).map((row) => <div key={row.label}><div className="mb-2 flex items-center justify-between text-sm"><span className="capitalize text-muted-foreground">{row.label.replaceAll("_", " ")}</span><span>{row.count}</span></div><Progress value={data.orders.length ? row.count / data.orders.length * 100 : 0} className="h-2" /></div>)}</CardContent></Card><Card className="border-amber-400/15 bg-amber-400/[0.04] shadow-none"><CardContent className="flex gap-3 p-5"><Truck className="mt-0.5 size-5 shrink-0 text-amber-300" /><div><p className="font-medium text-amber-200">RTO requires a shipping source</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Shopify does not provide a reliable universal RTO state. SignalDesk will not guess it from cancellations. Connect Shiprocket or another carrier in a later operations phase to report RTO accurately.</p></div></CardContent></Card></div>
    <Card className="border-white/[0.07] bg-card/60 shadow-none"><CardHeader><CardTitle>Campaign revenue</CardTitle><CardDescription>Orders grouped by Shopify UTM campaign</CardDescription></CardHeader><CardContent className="space-y-6">{campaigns.map((campaign) => <div key={campaign.name} className="grid items-center gap-3 sm:grid-cols-[1fr_120px_2fr]"><div><p className="font-mono text-sm">{campaign.name}</p><p className="text-xs text-muted-foreground">{campaign.orders} orders</p></div><p className="font-medium sm:text-right">{money(campaign.revenue)}</p><Progress value={(campaign.revenue / max) * 100} className="h-2" /></div>)}{!campaigns.length && <p className="text-sm text-muted-foreground">Import orders to populate reports.</p>}</CardContent></Card>
  </div></AppShell>;
}

function lifecycleRows(orders: Record<string, unknown>[]) { const counts = new Map<string, number>(); for (const order of orders) { const status = String(order.status ?? "open"); counts.set(status, (counts.get(status) ?? 0) + 1); } return ["open","fulfilled","cancelled","partially_refunded","refunded"].map((label) => ({ label, count: counts.get(label) ?? 0 })); }
